### ISSUE TITLE
wrong assignment in uint8_t* Coap PDU::malloc Payload(int len)

### ISSUE THREAD

**Issue by piotr276** [staropram/cantcoap#26]
Hi, I think that there are two wrong assignments in _uint8_t* Coap PDU::mallocPayload(int len)_ method

```
                // in the case of a realloc a few things are done differently to
		// a new allocation
		if(_pdu!=newPDU) {
			// adjust payload pointer to point into the new memory
			_payloadPointer = &_pdu[_pduLength+1];
			// and also set the payload marker if it wasn't already set
			if(markerSpace!=0) {
				_pdu[_pduLength] = 0xFF;
			}
		}

		_pdu = newPDU;
		_bufferLength = newLen;
```

instead assignment:

`_payloadPointer = &_pdu[_pduLength+1];`

I believe it should be:

`_payloadPointer = &newPDU[_pduLength+1];`

Same for:

`_pdu[_pduLength] = 0xFF;  <-----> newPDU[_pduLength] = 0xFF;`

Another solution is to move

`_pdu = newPDU`

right after the if statement:
```
if(_pdu!=newPDU) {
    _pdu = newPDU;
   (...)
}
_bufferLength = newLen;
```

and then rest of the method could be as original

If I'm wrong, please explain how it should be working.
Based on my experience in current form this is not working properly when **__pdu != newPDU_**

**Comment by staropram** [comment]
Thanks, I had a quick look and I think you are right. It's been a while since I looked at the code so I'll take a detailed look soon. Cheers

6 Oct 2021 17:01:44 piotr276 ***@***.***>:

**Comment by staropram** [comment]
Thanks for this, what a silly mistake I made there :)

I created a test case which catches the error and then fixed it by setting _pdu = newPDU
