### ISSUE TITLE
Not enough space for payload after reallocation

### ISSUE THREAD

**Issue by agrogoth** [staropram/cantcoap#27]
The calculation for reallocating payload space in mallocPayload seems to be incorrect. Please look at the attached test source file and the output generated by address sanitizer.

[test.cpp.zip](https://github.com/staropram/cantcoap/files/7482238/test.cpp.zip)
[addresssanitizer.log](https://github.com/staropram/cantcoap/files/7482239/addresssanitizer.log)

**Comment by staropram** [comment]
Thanks for this. -fsanitize=address would have saved that ever happening. Good to know.

I've fixed it. It was simple in the end, but only just had time to look at it.
